package entity

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// ShowtimeStatus represents showtime status
type ShowtimeStatus string

const (
	ShowtimeScheduled  ShowtimeStatus = "SCHEDULED"
	ShowtimeOngoing    ShowtimeStatus = "ONGOING"
	ShowtimeCompleted  ShowtimeStatus = "COMPLETED"
	ShowtimeCancelled  ShowtimeStatus = "CANCELLED"
)

// PriceTier represents pricing tiers
type PriceTier string

const (
	PriceTierStandard PriceTier = "STANDARD"
	PriceTierPremium  PriceTier = "PREMIUM"
	PriceTierDiscount PriceTier = "DISCOUNT"
	PriceTierHoliday  PriceTier = "HOLIDAY"
)

// Showtime represents a movie showtime
type Showtime struct {
	ID              uuid.UUID      `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	CinemaID        uuid.UUID      `gorm:"type:uuid;not null" json:"cinema_id"`
	ScreenID        uuid.UUID      `gorm:"type:uuid;not null" json:"screen_id"`
	MovieID         uuid.UUID      `gorm:"type:uuid;not null" json:"movie_id"`
	ShowDate        time.Time      `gorm:"type:date;not null" json:"show_date"`
	StartTime       string         `gorm:"type:time;not null" json:"start_time"` // HH:MM format
	EndTime         string         `gorm:"type:time;not null" json:"end_time"`
	PriceTier       PriceTier      `gorm:"type:varchar(20);default:'STANDARD'" json:"price_tier"`
	BasePrice       float64        `gorm:"type:decimal(10,2);default:10.00" json:"base_price"`
	TotalSeats      int            `gorm:"not null" json:"total_seats"`
	AvailableSeats  int            `gorm:"not null" json:"available_seats"`
	IsAutoGenerated bool           `gorm:"default:false" json:"is_auto_generated"`
	Status          ShowtimeStatus `gorm:"type:varchar(20);default:'SCHEDULED'" json:"status"`
	Version         int            `gorm:"default:0" json:"-"` // For optimistic locking
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	// Relations
	Cinema Cinema `gorm:"foreignKey:CinemaID" json:"cinema,omitempty"`
	Screen Screen `gorm:"foreignKey:ScreenID" json:"screen,omitempty"`
	Movie  Movie  `gorm:"foreignKey:MovieID" json:"movie,omitempty"`
}

// TableName sets the table name for Showtime
func (Showtime) TableName() string {
	return "showtimes"
}

// IsFull returns true if no seats are available
func (s *Showtime) IsFull() bool {
	return s.AvailableSeats <= 0
}

// IsUpcoming returns true if the showtime is in the future
func (s *Showtime) IsUpcoming() bool {
	return s.Status == ShowtimeScheduled
}

// OccupancyRate returns the occupancy rate as a percentage
func (s *Showtime) OccupancyRate() float64 {
	if s.TotalSeats == 0 {
		return 0
	}
	return float64(s.TotalSeats-s.AvailableSeats) / float64(s.TotalSeats) * 100
}
