// Package cinemav1 contains Go type stubs for the cinema.v1 protobuf definitions.
// This is a manual implementation since protoc is not available.
// In production, these would be auto-generated from .proto files using protoc-gen-go.
package cinemav1

// ==================== Auth Types ====================

type RegisterRequest struct {
	Email     string
	Password  string
	FirstName string
	LastName  string
	Phone     *string
}

type RegisterResponse struct {
	Success bool
	Message string
	User    *User
}

type LoginRequest struct {
	Email    string
	Password string
}

type LoginResponse struct {
	Success      bool
	AccessToken  string
	RefreshToken string
	ExpiresIn    int32
	User         *User
}

type RefreshTokenRequest struct {
	RefreshToken string
}

type RefreshTokenResponse struct {
	Success     bool
	AccessToken string
	ExpiresIn   int32
}

type LogoutRequest struct {
	RefreshToken string
}

type LogoutResponse struct {
	Success bool
	Message string
}

type GetCurrentUserRequest struct{}

type GetCurrentUserResponse struct {
	User *User
}

type User struct {
	Id            string
	Email         string
	FirstName     string
	LastName      string
	Phone         *string
	Role          string
	EmailVerified bool
	CreatedAt     string
}

// ==================== Movies Types ====================

type ListMoviesRequest struct {
	Page     int32
	Limit    int32
	Search   *string
	Genre    *string
	Format   *string
	IsActive *bool
}

type ListMoviesResponse struct {
	Movies     []*Movie
	Pagination *Pagination
}

type GetMovieRequest struct {
	Id string
}

type GetMovieResponse struct {
	Movie *Movie
}

type GetNowShowingRequest struct {
	CinemaId *string
	Page     int32
	Limit    int32
}

type GetNowShowingResponse struct {
	Movies     []*Movie
	Pagination *Pagination
}

type CreateMovieRequest struct {
	Title           string
	OriginalTitle   *string
	Description     *string
	Duration        int32
	ReleaseDate     string
	Rating          *string
	Language        *string
	Genres          []string
	Director        *string
	Cast            []string
	PosterUrl       *string
	BackdropUrl     *string
	TrailerUrl      *string
	Format          string
	PopularityScore float64
}

type CreateMovieResponse struct {
	Success bool
	Movie   *Movie
}

type UpdateMovieRequest struct {
	Id              string
	Title           *string
	Description     *string
	Duration        *int32
	Rating          *string
	Genres          []string
	PosterUrl       *string
	BackdropUrl     *string
	TrailerUrl      *string
	IsActive        *bool
	PopularityScore *float64
}

type UpdateMovieResponse struct {
	Success bool
	Movie   *Movie
}

type DeleteMovieRequest struct {
	Id string
}

type DeleteMovieResponse struct {
	Success bool
	Message string
}

type Movie struct {
	Id              string
	Title           string
	OriginalTitle   *string
	Description     *string
	Duration        int32
	ReleaseDate     string
	Rating          *string
	Language        *string
	Genres          []string
	Director        *string
	Cast            []string
	PosterUrl       *string
	BackdropUrl     *string
	TrailerUrl      *string
	Format          string
	IsActive        bool
	PopularityScore float64
	CreatedAt       string
	UpdatedAt       string
}

type Pagination struct {
	Page       int32
	Limit      int32
	Total      int32
	TotalPages int32
}

// ==================== Showtimes Types ====================

type ListShowtimesRequest struct {
	CinemaId string
	MovieId  *string
	Date     string
}

type ListShowtimesResponse struct {
	Showtimes []*Showtime
}

type GetShowtimeRequest struct {
	Id string
}

type GetShowtimeResponse struct {
	Showtime *Showtime
}

type GetSeatMapRequest struct {
	ShowtimeId string
}

type GetSeatMapResponse struct {
	ShowtimeId     string
	TotalSeats     int32
	AvailableSeats int32
	Layout         *SeatLayout
}

type CreateShowtimeRequest struct {
	ScreenId  string
	MovieId   string
	CinemaId  string
	ShowDate  string
	StartTime string
	EndTime   string
}

type CreateShowtimeResponse struct {
	Success  bool
	Showtime *Showtime
}

type GenerateScheduleRequest struct {
	CinemaId    string
	Date        string
	MovieIds    []string
	Preferences *SchedulePreferences
}

type GenerateScheduleResponse struct {
	Success    bool
	TotalShows int32
	Showtimes  []*Showtime
	Metrics    *ScheduleMetrics
}

type Showtime struct {
	Id              string
	ScreenId        string
	MovieId         string
	CinemaId        string
	ShowDate        string
	StartTime       string
	EndTime         string
	PriceTier       string
	TotalSeats      int32
	AvailableSeats  int32
	IsAutoGenerated bool
	Status          string
	Movie           *Movie
	Screen          *Screen
}

type Screen struct {
	Id               string
	CinemaId         string
	Name             string
	Capacity         int32
	ScreenType       string
	SupportedFormats []string
}

type SeatLayout struct {
	Rows []*SeatRow
}

type SeatRow struct {
	Label string
	Seats []*Seat
}

type Seat struct {
	Id         string
	SeatNumber int32
	Type       string
	Status     string
	Price      float64
	Position   *Position
}

type Position struct {
	X float64
	Y float64
}

type SchedulePreferences struct {
	MinShowsPerMovie int32
	MaxShowsPerMovie int32
}

type ScheduleMetrics struct {
	AvgUtilization float64
	PeakShows      int32
}

// ==================== Bookings Types ====================

type HoldSeatsRequest struct {
	ShowtimeId string
	SeatIds    []string
}

type HoldSeatsResponse struct {
	Success   bool
	HoldId    string
	ExpiresAt string
	Seats     []*Seat
	Pricing   *PriceBreakdown
}

type ConfirmBookingRequest struct {
	HoldId        string
	PromoCode     *string
	PaymentMethod string
}

type ConfirmBookingResponse struct {
	Success          bool
	BookingId        string
	BookingReference string
	Status           string
	FinalAmount      float64
	PaymentUrl       string
}

type GetBookingRequest struct {
	Id string
}

type GetBookingResponse struct {
	Booking *Booking
}

type ListUserBookingsRequest struct {
	Page  int32
	Limit int32
}

type ListUserBookingsResponse struct {
	Bookings   []*Booking
	Pagination *Pagination
}

type CancelBookingRequest struct {
	Id     string
	Reason string
}

type CancelBookingResponse struct {
	Success      bool
	Message      string
	RefundAmount float64
}

type Booking struct {
	Id               string
	BookingReference string
	UserId           string
	ShowtimeId       string
	NumTickets       int32
	TotalAmount      float64
	DiscountAmount   float64
	FinalAmount      float64
	PromoCode        *string
	BookingStatus    string
	PaymentStatus    string
	BookedAt         string
	Showtime         *Showtime
	Seats            []*BookedSeat
}

type BookedSeat struct {
	Row        string
	SeatNumber int32
	Type       string
	Price      float64
}

type PriceBreakdown struct {
	SeatPrices    []*SeatPrice
	Subtotal      float64
	Discounts     []*Discount
	TotalDiscount float64
	Tax           float64
	FinalAmount   float64
}

type SeatPrice struct {
	SeatId     string
	BasePrice  float64
	FinalPrice float64
	Breakdown  []string
}

type Discount struct {
	Type        string
	Code        string
	Description string
	Amount      float64
}

// ==================== Pricing Types ====================

type CalculatePriceRequest struct {
	ShowtimeId string
	SeatIds    []string
	PromoCode  *string
	UserId     *string
}

type CalculatePriceResponse struct {
	PriceBreakdown *PriceBreakdown
}

type ValidatePromoCodeRequest struct {
	Code       string
	Subtotal   float64
	ShowtimeId string
}

type ValidatePromoCodeResponse struct {
	Valid    bool
	Message  string
	Discount *Discount
}
