// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cinemaos-backend/internal/app/postgres"
	"cinemaos-backend/internal/app/redis"
	"cinemaos-backend/internal/config"
	"cinemaos-backend/internal/pkg/logger"
	"cinemaos-backend/internal/pkg/tracer"
	"cinemaos-backend/internal/provider"
	"cinemaos-backend/internal/server"
)

// Injectors from wire.go:

// InitializeApplication wires up all dependencies using Wire
func InitializeApplication(configPath string) (*Application, error) {
	config, err := provider.ProvideConfig(configPath)
	if err != nil {
		return nil, err
	}
	logger, err := provider.ProvideLogger(config)
	if err != nil {
		return nil, err
	}
	jwtManager := provider.ProvideJWTManager(config)
	authMiddleware := provider.ProvideAuthMiddleware(jwtManager, logger)
	database, err := provider.ProvideDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	userRepository := provider.ProvideUserRepository(database)
	refreshTokenRepository := provider.ProvideRefreshTokenRepository(database)
	passwordResetTokenRepository := provider.ProvidePasswordResetTokenRepository(database)
	passwordManager := provider.ProvidePasswordManager()
	service := provider.ProvideAuthService(userRepository, refreshTokenRepository, passwordResetTokenRepository, jwtManager, passwordManager, logger, config)
	validator := provider.ProvideValidator()
	authHandler := provider.ProvideAuthHandler(service, validator)
	client, err := provider.ProvideRedis(config, logger)
	if err != nil {
		return nil, err
	}
	healthHandler := provider.ProvideHealthHandler(config, database, client)
	movieRepository := provider.ProvideMovieRepository(database)
	movieService := provider.ProvideMovieService(movieRepository, logger)
	showtimeRepository := provider.ProvideShowtimeRepository(database)
	cinemaRepository := provider.ProvideCinemaRepository(database)
	screenRepository := provider.ProvideScreenRepository(database)
	showtimeService := provider.ProvideShowtimeService(showtimeRepository, movieRepository, cinemaRepository, screenRepository, logger)
	movieHandler := provider.ProvideMovieHandler(movieService, showtimeService, validator)
	seatRepository := provider.ProvideSeatRepository(database)
	cinemaService := provider.ProvideCinemaService(cinemaRepository, screenRepository, seatRepository, logger)
	cinemaHandler := provider.ProvideCinemaHandler(cinemaService, validator)
	showtimeHandler := provider.ProvideShowtimeHandler(showtimeService, validator)
	engine := provider.ProvideRouter(config, logger, authMiddleware, authHandler, healthHandler, movieHandler, cinemaHandler, showtimeHandler)
	server := provider.ProvideHTTPServer(config, engine, logger)
	tracer, err := provider.ProvideTracer(config)
	if err != nil {
		return nil, err
	}
	application := &Application{
		Server:      server,
		Logger:      logger,
		DB:          database,
		RedisClient: client,
		Tracer:      tracer,
		Config:      config,
	}
	return application, nil
}

// wire.go:

// Application holds all the components needed to run the server
type Application struct {
	Server      *server.Server
	Logger      *logger.Logger
	DB          *postgres.Database
	RedisClient *redis.Client
	Tracer      *tracer.Tracer
	Config      *config.Config
}
