package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ShowtimeStatus string

const (
	ShowtimeScheduled  ShowtimeStatus = "SCHEDULED"
	ShowtimeOngoing    ShowtimeStatus = "ONGOING"
	ShowtimeCompleted  ShowtimeStatus = "COMPLETED"
	ShowtimeCancelled  ShowtimeStatus = "CANCELLED"
)

type Showtime struct {
	ID              uuid.UUID      `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	ScreenID        uuid.UUID      `gorm:"type:uuid;not null" json:"screen_id"`
	MovieID         uuid.UUID      `gorm:"type:uuid;not null" json:"movie_id"`
	CinemaID        uuid.UUID      `gorm:"type:uuid;not null" json:"cinema_id"`
	ShowDate        time.Time      `gorm:"type:date;not null" json:"show_date"`
	StartTime       string         `gorm:"type:time;not null" json:"start_time"`
	EndTime         string         `gorm:"type:time;not null" json:"end_time"`
	PriceTier       string         `gorm:"default:'STANDARD'" json:"price_tier"`
	TotalSeats      int            `gorm:"not null" json:"total_seats"`
	AvailableSeats  int            `gorm:"not null" json:"available_seats"`
	IsAutoGenerated bool           `gorm:"default:false" json:"is_auto_generated"`
	Status          ShowtimeStatus `gorm:"type:varchar(20);default:'SCHEDULED'" json:"status"`
	Version         int            `gorm:"default:0" json:"version"` // For optimistic locking
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Screen       Screen        `gorm:"foreignKey:ScreenID;constraint:OnDelete:CASCADE" json:"-"`
	Movie        Movie         `gorm:"foreignKey:MovieID;constraint:OnDelete:CASCADE" json:"-"`
	Cinema       Cinema        `gorm:"foreignKey:CinemaID;constraint:OnDelete:CASCADE" json:"-"`
	Bookings     []Booking     `gorm:"foreignKey:ShowtimeID" json:"-"`
	BookingSeats []BookingSeat `gorm:"foreignKey:ShowtimeID" json:"-"`
}

type BookingStatus string

const (
	BookingPending   BookingStatus = "PENDING"
	BookingConfirmed BookingStatus = "CONFIRMED"
	BookingCompleted BookingStatus = "COMPLETED"
	BookingCancelled BookingStatus = "CANCELLED"
	BookingRefunded  BookingStatus = "REFUNDED"
)

type PaymentStatus string

const (
	PaymentPending  PaymentStatus = "PENDING"
	PaymentPaid     PaymentStatus = "PAID"
	PaymentFailed   PaymentStatus = "FAILED"
	PaymentRefunded PaymentStatus = "REFUNDED"
)

type Booking struct {
	ID               uuid.UUID      `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	BookingReference string         `gorm:"uniqueIndex;not null" json:"booking_reference"`
	UserID           *uuid.UUID     `gorm:"type:uuid" json:"user_id"`
	ShowtimeID       uuid.UUID      `gorm:"type:uuid;not null" json:"showtime_id"`
	GuestEmail       *string        `json:"guest_email"`
	GuestName        *string        `json:"guest_name"`
	GuestPhone       *string        `json:"guest_phone"`
	NumTickets       int            `gorm:"not null" json:"num_tickets"`
	TotalAmount      float64        `gorm:"type:decimal(10,2);not null" json:"total_amount"`
	DiscountAmount   float64        `gorm:"type:decimal(10,2);default:0" json:"discount_amount"`
	FinalAmount      float64        `gorm:"type:decimal(10,2);not null" json:"final_amount"`
	PromoCode        *string        `json:"promo_code"`
	BookingStatus    BookingStatus  `gorm:"type:varchar(20);default:'PENDING'" json:"booking_status"`
	PaymentStatus    PaymentStatus  `gorm:"type:varchar(20);default:'PENDING'" json:"payment_status"`
	PaymentMethod    *string        `json:"payment_method"`
	BookedAt         time.Time      `gorm:"default:CURRENT_TIMESTAMP" json:"booked_at"`
	ExpiresAt        *time.Time     `json:"expires_at"`
	ConfirmedAt      *time.Time     `json:"confirmed_at"`
	CancelledAt      *time.Time     `json:"cancelled_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"index" json:"-"`

	User         *User         `gorm:"foreignKey:UserID;constraint:OnDelete:SET NULL" json:"-"`
	Showtime     Showtime      `gorm:"foreignKey:ShowtimeID;constraint:OnDelete:CASCADE" json:"-"`
	BookingSeats []BookingSeat `gorm:"foreignKey:BookingID" json:"-"`
	Payments     []Payment     `gorm:"foreignKey:BookingID" json:"-"`
}

type BookingSeat struct {
	ID         uuid.UUID      `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	BookingID  uuid.UUID      `gorm:"type:uuid;not null" json:"booking_id"`
	SeatID     uuid.UUID      `gorm:"type:uuid;not null" json:"seat_id"`
	ShowtimeID uuid.UUID      `gorm:"type:uuid;not null" json:"showtime_id"`
	Price      float64        `gorm:"type:decimal(10,2);not null" json:"price"`
	CreatedAt  time.Time      `json:"created_at"`
	DeletedAt  gorm.DeletedAt `gorm:"index" json:"-"`

	Booking  Booking  `gorm:"foreignKey:BookingID;constraint:OnDelete:CASCADE" json:"-"`
	Seat     Seat     `gorm:"foreignKey:SeatID;constraint:OnDelete:CASCADE" json:"-"`
	Showtime Showtime `gorm:"foreignKey:ShowtimeID;constraint:OnDelete:CASCADE" json:"-"`
}

func (BookingSeat) TableName() string {
	return "booking_seats"
}

type Payment struct {
	ID                   uuid.UUID      `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	BookingID            uuid.UUID      `gorm:"type:uuid;not null" json:"booking_id"`
	PaymentReference     string         `gorm:"uniqueIndex;not null" json:"payment_reference"`
	PaymentGateway       *string        `json:"payment_gateway"`
	GatewayTransactionID *string        `json:"gateway_transaction_id"`
	Amount               float64        `gorm:"type:decimal(10,2);not null" json:"amount"`
	Currency             string         `gorm:"default:'USD'" json:"currency"`
	PaymentStatus        PaymentStatus  `gorm:"type:varchar(20);default:'PENDING'" json:"payment_status"`
	PaymentMethod        *string        `json:"payment_method"`
	CardLastFour         *string        `json:"card_last_four"`
	FailureReason        *string        `gorm:"type:text" json:"failure_reason"`
	GatewayResponse      *string        `gorm:"type:jsonb" json:"gateway_response"`
	PaidAt               *time.Time     `json:"paid_at"`
	RefundedAt           *time.Time     `json:"refunded_at"`
	RefundAmount         *float64       `gorm:"type:decimal(10,2)" json:"refund_amount"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            gorm.DeletedAt `gorm:"index" json:"-"`

	Booking Booking `gorm:"foreignKey:BookingID;constraint:OnDelete:CASCADE" json:"-"`
}

type PricingRule struct {
	ID            uuid.UUID      `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	CinemaID      *uuid.UUID     `gorm:"type:uuid" json:"cinema_id"`
	Name          string         `gorm:"not null" json:"name"`
	RuleType      string         `gorm:"not null" json:"rule_type"`
	SeatType      *SeatType      `json:"seat_type"`
	DayOfWeek     []int          `gorm:"type:int[]" json:"day_of_week"`
	TimeRange     *string        `gorm:"type:jsonb" json:"time_range"`
	PriceModifier float64        `gorm:"type:decimal(10,2);not null" json:"price_modifier"`
	ModifierType  string         `gorm:"default:'FIXED'" json:"modifier_type"`
	Priority      int            `gorm:"default:0" json:"priority"`
	IsActive      bool           `gorm:"default:true" json:"is_active"`
	ValidFrom     *time.Time     `gorm:"type:date" json:"valid_from"`
	ValidUntil    *time.Time     `gorm:"type:date" json:"valid_until"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"index" json:"-"`

	Cinema *Cinema `gorm:"foreignKey:CinemaID;constraint:OnDelete:CASCADE" json:"-"`
}

func (PricingRule) TableName() string {
	return "pricing_rules"
}

type Promocode struct {
	ID                uuid.UUID      `gorm:"type:uuid;primary_key;default:gen_random_uuid()" json:"id"`
	Code              string         `gorm:"uniqueIndex;not null" json:"code"`
	Description       *string        `gorm:"type:text" json:"description"`
	DiscountType      string         `gorm:"not null" json:"discount_type"`
	DiscountValue     float64        `gorm:"type:decimal(10,2);not null" json:"discount_value"`
	MaxDiscount       *float64       `gorm:"type:decimal(10,2)" json:"max_discount"`
	MinPurchase       *float64       `gorm:"type:decimal(10,2)" json:"min_purchase"`
	UsageLimit        *int           `json:"usage_limit"`
	UsageCount        int            `gorm:"default:0" json:"usage_count"`
	ValidFrom         time.Time      `gorm:"not null" json:"valid_from"`
	ValidUntil        time.Time      `gorm:"not null" json:"valid_until"`
	IsActive          bool           `gorm:"default:true" json:"is_active"`
	ApplicableCinemas []string       `gorm:"type:uuid[]" json:"applicable_cinemas"`
	ApplicableMovies  []string       `gorm:"type:uuid[]" json:"applicable_movies"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"index" json:"-"`
}
